### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by aufau**
Hi,
I've restored linux support with CMake.
I made my best not to break msvc build but apparently our environments are slightly different (I used VC++ 2010 express). I had to make some syntax changes here and there due to GCC being much more strict than msvc. OpenGL declarations code is a mess but I cleaned up the linux part (no need for glext.h).

Unfortunately there is still a major bug left. Some (all?) effects are visible on top of entities and others don't show up at all. Same code runs ok on windows. I also tested ioquake/jedi-outcast on linux and it looks good. Some stencil buffer issues perhaps? I don't really know this part of the engine. Do you have any ideas what may be cause of this?
shot 0004

### CODE REVIEW

**Comment by D8174** [comment]
I had a problem that looks the same (black lines), [here.](https://github.com/syrobee/jedi-outcast/issues/2)
I fixed it by replacing all GL_CLAMP with GL_CLAMP_TO_EDGE.

**Comment by D8174** [comment]
This builds for me fine with these commits on Ubuntu x86_64 with i386 libs but for some reason my menus have no text.

**Comment by aufau** [comment]
Didn't you forget to add +set fs_game mme commandline and download appropriate files from jkhub.org?

Apparently there was an error in sdl/sdl_glimp.cpp See the latest commit. I guess I should review changes I made there.
I'm not sure why you had to replace all GL_CLAMP occurrences in your fork. R_FindImageFile and R_CreateImage should do this by themselves.
Thanks for figuring it out. I wouldn't have done it myself.

On a side note:
I stopped working on this as well as on my ioquake/jedi-outcast fork (as I engaged more into jk2 community development) but I realize now that this these commits are far from "restoring linux support" eg. sound recording has no chance to work without some major changes. On the other hand most of the bugs in my ioquake/jedi-outcast fork - which I didn't care to fix - appear to be related to qvm so jomme may be unaffected. I'll try to find time to work on it in the future.

**Comment by D8174** [comment]
> Didn't you forget to add +set fs_game mme commandline

Oops.

**Comment by entdark** [comment]
Hi, thank you for taking a part in maintaining joMME, and I'd like to pull your request, but could you, please fix some stuff before?

```
// trap_SetUserCmdValue( 0, 1.0f, 0.0f, 0.0f, 0.0f, 0, 0, qfalse );
->
trap_SetUserCmdValue( 0.0f, 1.0f, 0.0f, 0.0f );

// trap_FX_PlayEffectID(ci->effectOverride, cent->lerpOrigin, forward, -1, -1);
->
trap_FX_PlayEffectID(ci->effectOverride, cent->lerpOrigin, forward);

#define CLIENT_WINDOW_TITLE "Jedi Knight 2: Jedi Outcast Movie Maker's Edition"
#define CLIENT_WINDOW_MIN_TITLE "JOMME"
->
#define CLIENT_WINDOW_TITLE "Jedi Outcast"
#define CLIENT_WINDOW_MIN_TITLE "JO"
```

Rest is fine.
First two was just blindly copy-pasted from jaMME. The 3rd thing is needed for q3e minimizer (it detects the game by window title). Optionally you can apply it for WIN32 only, so linux and mac will have the new title.
I'd do it myself but I am busy right now, unfortunately.

**Comment by entdark** [comment]
> Unfortunately there is still a major bug left. Some (all?) effects are visible on top of entities and others don't show up at all.

I can only take a guess that it's related to R_RadixSort that replaced qsortFast and its big/little endian preprocessor. That was done to increase the amount of ref entities from 2048 to 65536: https://github.com/entdark/jk2mp/commit/7449d6314030fc0a696fdaab5b5685dfb6a087d3

**Comment by aufau** [comment]
Good call. Renderer seems to work allright now.

CLIENT_WINDOW_ are for Linux only already.

Unfortunately this still isn't ready to get pulled as sound doesn't work (the ioquake port I based my work on is limited to OpenAL) and I haven't really tested it. I'll try to find some time and work on it.

**Comment by entdark** [comment]
Thank you for the commit. Waiting for audio working then yet. x]
Oh yeah, sorry about it. The original engine supported OpenAL, but since I remade the sound engine fully then I had to get rid of it. Check openjk with their linux support, they use SDL for DMA (current and original sound logic in joMME).

**Comment by entdark** [comment]
I gonna add some stuff to joMME now, and not to break sync I pulled the request, just add fixed linux audio in the next pull request.

**Pull request merged**
